doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute  # Utilisation des attributs
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            driver: 'pdo_mysql'
            url: '%env(resolve:DATABASE_URL)%'
            charset: utf8mb4
            server_version: '5.7'
        orm:
            auto_generate_proxy_classes: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute  # Utilisation des attributs
                    dir: '%kernel.project_dir%/src/Entity'
                    prefix: 'App\Entity'

when@prod:
    doctrine:
        dbal:
            url: '%env(resolve:DATABASE_URL)%'
        orm:
            auto_generate_proxy_classes: true
            naming_strategy: doctrine.orm.naming_strategy.underscore
            auto_mapping: true
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            mappings:
                App:
                    is_bundle: false
                    type: attribute  # Utilisation des attributs
                    dir: '%kernel.project_dir%/src/Entity'
                    prefix: 'App\Entity'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
