security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        utilisateurs_provider:
            entity:
                class: App\Entity\Utilisateur
                property: nom

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: utilisateurs_provider
            form_login:
                login_path: connexion
                check_path: connexion
                default_target_path: /projet  # 🔥 ICI ➔ toujours /projet après connexion
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
