security:
    enable_authenticator_manager: true  # ✅ Nécessaire pour activer login/logout automatiques

    # 🔐 Hachage du mot de passe
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    # 👤 Chargement des utilisateurs via entité Utilisateur
    providers:
        utilisateurs_provider:
            entity:
                class: App\Entity\Utilisateur
                property: nom

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: utilisateurs_provider

            form_login:
                login_path: connexion      # URL de connexion (route "connexion")
                check_path: connexion

            logout:
                path: logout               # URL de déconnexion
                target: /                  # Redirection après logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
